export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const LOAD_API_CONFIG = 'LOAD_API_CONFIG';
export const SEND_MESSAGE_REQUESTED = 'SEND_MESSAGE_REQUESTED';
export const SEND_MESSAGE_SUCCEEDED = 'SEND_MESSAGE_SUCCEEDED';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
